
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_SOC(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [7:0] out_reg_1;
wire [7:0] in_reg_2;
wire [7:0] out_reg_2;

wire [7:0] in_C0;
wire [7:0] in_C1;
wire [7:0] in_C2;
wire [7:0] in_C3;
wire [7:0] in_C4;
wire [7:0] in_C5;
wire [7:0] in_C6;
wire [7:0] in_C7;

wire [7:0] out_C0;
wire [7:0] out_C1;
wire [7:0] out_C2;
wire [7:0] out_C3;
wire [7:0] out_C4;
wire [7:0] out_C5;
wire [7:0] out_C6;
wire [7:0] out_C7;

wire [7:0] leds;

wire [3:0] units;
wire [3:0] tens;
wire [1:0] hunds;

//=======================================================
//  Structural coding
//=======================================================

registro r1(.entrada(SW[7:0]),.reloj(KEY[1]),.salida(out_reg_1));

registro_salida r2(.entrada(in_reg_2),.salida(leds));

C c1(
	.N1(in_C0), 
	.N2(in_C1), 
	.N3(in_C2), 
	.N4(in_C3), 
	.N5(in_C4), 
	.N6(in_C5), 
	.N7(in_C6), 
	.N8(in_C7), 
	.S1(out_C0), 
	.S2(out_C1), 
	.S3(out_C2), 
	.S4(out_C3), 
	.S5(out_C4), 
	.S6(out_C5), 
	.S7(out_C6), 
	.S8(out_C7));

nios_2 procesador(
	.clk_clk(CLOCK_50),
	.pio_input_0_export(out_C0),
	.pio_input_1_export(out_C1),
	.pio_input_2_export(out_C2),
	.pio_input_3_export(out_C3),
	.pio_input_4_export(out_C4),
	.pio_input_5_export(out_C5),
	.pio_input_6_export(out_C6),
	.pio_input_7_export(out_C7),
	.pio_output_0_export(in_C0),
	.pio_output_1_export(in_C1),
	.pio_output_2_export(in_C2),
	.pio_output_3_export(in_C3),
	.pio_output_4_export(in_C4),
	.pio_output_5_export(in_C5),
	.pio_output_6_export(in_C6),
	.pio_output_7_export(in_C7),
	.pioinput_export(out_reg_1),
	.piooutput_export(in_reg_2),
	.reset_reset_n(KEY[0])
	);




assign LEDR = leds;

BIN2BCD bin2bcd( .entrada(leds), .units(units), .tens(tens), .hunds(hunds) );

BCD2HEX bin2hexUnits(.entrada(units), .salida(HEX0));

BCD2HEX bin2hexTens(.entrada(tens), .salida(HEX1));

BCD2HEX bin2hexHunds(.entrada(hunds), .salida(HEX2));

	assign HEX5[6:0] = 7'b1111111;
	assign HEX4[6:0] = 7'b1111111;
	assign HEX3[6:0] = 7'b1111111;

endmodule
